### ISSUE TITLE
Initial Guidelines

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/contributors#1]
@orta and I had a lot of fun writing up [Moya's contributor guidelines](https://github.com/Moya/contributors), and I think we need something similar for this org. 

Necessary things, I think:
- Code of conduct
- Expectations of contributors (Moya's is basically "don't stress about this")
- How to consider moving a repo to the org (probably open an issue on this repo to discuss?)
- ???

I feel strongly that we should have a "contributors" team and, once anyone sends a PR that gets merged, they should be added to that team and have push access. We can use GitHub to protect master branches against force-pushing to mitigate potential problems, but this really helps people feel a sense of ownership of the project and encourages them to contribute more.

**Comment by bontoJR** [comment]
> I feel strongly that we should have a "contributors" team and, once anyone sends a PR that gets merged, they should be added to that team and have push access. 

I agree on that.

> We can use GitHub to protect master branches against force-pushing to mitigate potential problems, but this really helps people feel a sense of ownership of the project and encourages them to contribute more.

This is a very nice strategy. One little thing, I would prefer to keep guides.rxswift.org as the only exception. I am still working on rearranging the README in RxSwift repo and move some stuff there, but I am still not very happy about the result. :cry:

I will iterate more on that. :)

**Comment by ashfurrow** [comment]
That makes sense! Repos have granular permissions settings, so there's nothing incompatible with keeping guides on its own.

If that's the case, later this morning I'll set up the team and maybe work with Orta on an initial PR to this repo with guidelines :tada:

**Comment by esttorhe** [comment]
Hi there; thanks for the invite on this Organization :smile: 

Would love to read some more on the `README` since I'm no :100: sure what's this all about :smile:

**Comment by esttorhe** [comment]
Related to the teams; I think having the `Contributors` works and maybe have an `Admin` group?
Or just by marking those we want as `Owners` will suffice?

**Comment by ashfurrow** [comment]
Yeah, the Owners should suffice. We've never used the Admin group for anything on Moya.
