### ISSUE TITLE
RxSegue

### ISSUE THREAD

**Issue by sergdort** [RxSwiftCommunity/contributors#10]
Hi, guys !
I've made [RxSegue](https://github.com/sergdort/RxSegue)
It's contains of couple reactive units to abstract navigation routine
If you think it could be useful, will be have to contribute to the community :)

**Comment by ashfurrow** [comment]
Looks really cool! What can we do to support you? We can add you to [the list of RxSwift community projects](http://community.rxswift.org), and/or we can transfer your library to our organization, whatever works for you!

**Comment by sergdort** [comment]
Well, I will be very honored, if my project will be in your organization :)

**Comment by sergdort** [comment]
Do I need any permissions to transfer my repo?

**Comment by ashfurrow** [comment]
Awesome! I've invited you to the org, and you can transfer the repo after that. [Here's a previous example](https://github.com/RxSwiftCommunity/Action/issues/15) where we did a transfer, and includes tasks we did with explanations. It's deceptively easy :smile: Make sure to take a look at the [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) too, and let me know if I can answer any questions, or can be of any help :bow:

**Comment by sergdort** [comment]
Hi, guys. 
Looks like I've made all required steps, so [RxSegue](https://github.com/RxSwiftCommunity/RxSegue) is now part of community 🌎🎉🎉

If, you see that I missed some, please let me know 😀

**Comment by sergdort** [comment]
Thank you very much for the invitation 😊

**Comment by ashfurrow** [comment]
Awesome, I think this is closed, eh?
