### ISSUE TITLE
RxGesture

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/contributors#11]
Hey guys was talking about this one yesterday to @bontoJR and this morning felt like a good enough tim e to push the code to GitHub: https://github.com/icanzilb/RxGesture

Often times I need to observe taps not only on buttons but also on other views (it makes sense since they can all receive touches, right) - often times image views which the user taps or swipes to see a larger preview, etc.

Further I noticed often I need to attach more gesture recognizers to the same view - like when I'm interested in a horizontal swipe not minding if left or right direction.

So `RxGesture` allows for an easy way to observe multiple gestures on any view - there's an example app in the repo, which I think shows well what it does.

Next I can imagine adding pans and maybe a shake too? Anyway - for now just checking if it looks interesting to any of you guys and if so polish it up and transfer to the organization.

**Comment by ashfurrow** [comment]
Awesome! Thanks Marin. I've invited you to the org, and if you want, you can transfer the repo. A PR to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io would probably make sense too. Here's a previous example where we did a transfer, and includes tasks we did with explanations.

**Comment by icanzilb** [comment]
@ashfurrow thanks for the invite :+1: I'll wait few days before pushing to the organization cz since it's now in the open I got some feedback how to improve the code. Then I'll transfer it when I'm sure it's all okay.

Btw - where it says "Here's a previous example" there is no link to that :)

**Comment by ashfurrow** [comment]
Ha, oops. Example is here: https://github.com/RxSwiftCommunity/Action/issues/15

**Comment by icanzilb** [comment]
[x] tidied up the code and any mentions of Marin Todorov
[x] updated the remote url of the podspec
[x] cleaned up the README
[x] updated the LICENSE copyright

I think it's ready for a hand off

**Comment by icanzilb** [comment]
Thanks @ashfurrow - it's done :+1:

**Comment by ashfurrow** [comment]
Awesome! Want to add to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io ?
