### ISSUE TITLE
RxMultipeer

### ISSUE THREAD

**Issue by nathankot** [RxSwiftCommunity/contributors#12]
I've written a RxSwift wrapper around MultipeerConnectivity that also has the added benefit of being testable using the adapter pattern: https://github.com/nathankot/NKMultipeer

Only just recently discovered RxSwiftCommunity but I'm happy to rename it to `RxMultipeer` and get it namespaced under this organization if there's interest :)

**Comment by ashfurrow** [comment]
Super cool! Looks awesome :tada: You're welcome to join, you can see a series of steps on how we've moved other repos under the org here: https://github.com/RxSwiftCommunity/contributors/issues/4

I've invited you to join the organization – if you have any questions about the process, don't hesitate to reach out. Thanks for contribution to the RxSwift and iOS open source communities!

**Comment by nathankot** [comment]
Awesome =D I'll be moving the repo over, over the weekend.
