### ISSUE TITLE
I would like to add my project RxStarscream to RxSwiftCommunity

### ISSUE THREAD

**Issue by GuyKahlon** [RxSwiftCommunity/contributors#13]
A lightweight extension to Starscream to track WebSocket events using RxSwift observables.

For more details:
https://github.com/GuyKahlon/RxStarscream.

Thanks,
Guy

**Comment by ashfurrow** [comment]
Very cool! Love the logo. Are you looking to only have it live on http://community.rxswift.org or would you like to migrate it to the organization? Happy to do whatever I can to help.

**Comment by GuyKahlon** [comment]
Hey @ashfurrow I'm glad to hear you like it (and the logo :)).
I would like to migrate it to the organization, I would like also to join into the organization, I have a few more Rx stuff to share with you.

Thanks for the help.

**Comment by ashfurrow** [comment]
Awesome! I've invited you to the org, so you should be set. Our contributor guidelines are [here](https://github.com/RxSwiftCommunity/contributors), let me know if you have any questions.

Here's an example of when someone has done this before: https://github.com/RxSwiftCommunity/contributors/issues/11 Let me know if I can help 👍

**Comment by GuyKahlon** [comment]
Hey @ashfurrow, thank you for the invitation 😃

Looks like I've made all required steps and RxStarscream is now part of the RxSwiftCommunity.
If, you see that I missed some, please let me know and I'll fix it.

**Comment by ashfurrow** [comment]
Cool, looks good! Should probably be added to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io . We should think of how to add unit tests and continuous integration, want to open an issue on the repo?

**Comment by GuyKahlon** [comment]
I've added the project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io under **Projects that Extend Other Projects with RxSwift**

I've opened issues for 'Add Unit Tests' and 'Add CI' on the repo, I'm starting to think who to add Unit Test (if you have any thoughts, how to do that please let me know), and after that I'll add a CI.

**Comment by ashfurrow** [comment]
Cool, I'm going to close this issue since it looks wrapped up. Feel free to re-open.
