### ISSUE TITLE
I want to add my project RxEventHub to RxSwiftCommunity

### ISSUE THREAD

**Issue by zzdjk6** [RxSwiftCommunity/contributors#14]
`RxEventHub` is an event hub based on `RxSwift`, it makes multicasting event easy, type-safe and error-free, it's intent to replace usage of `NSNotificationCenter` in most cases.

Project Github: [https://github.com/zzdjk6/RxEventHub](https://github.com/zzdjk6/RxEventHub)

Please review and consider adding it into RxSwiftCommunity, thanks.

**Comment by ashfurrow** [comment]
Looks nice, great readme :+1: I'll invite you to the org. Here are our contributor guidelines: https://github.com/RxSwiftCommunity/contributors And here's an example of when we've moved a repo over already: https://github.com/RxSwiftCommunity/contributors/issues/11 Please let me know if you have any questions or if I can be of help.

**Comment by zzdjk6** [comment]
Thanks for such quick reply, I'm preparing the MOVE.

I read the issue be referred, and come up below checklist:

[]Update copyright in code
[]Update copyright in LICENSE 
[]Update podspecs with new remote URL
[]Update CI badge
[]Update CI settings
[]Update README
[]Fork the repo back to my personal account

I'd like to know should I transfer the ownership first? or should I finish the check list first?

@ashfurrow

**Comment by ashfurrow** [comment]
Whatever makes sense for you! I usually transfer first.

**Comment by zzdjk6** [comment]
Thanks, I'll do transfer first too.

**Comment by zzdjk6** [comment]
I have done all items on checklist:

[x]Transfer the repo's ownership
[x]Fork the repo back to my personal account
[x]Update copyright in code
[x]Update copyright in LICENSE
[x]Update README
[x]Update podspecs with new remote URL
[x]Update CI badge
[x]Update CI settings

May you help check if this MOVE is successfully done?

**Comment by ashfurrow** [comment]
Looks great! The only missing thing is the CI badge is still pointing to http://img.shields.io/travis/zzdjk6/RxEventHub.svg?style=flat instead of http://img.shields.io/travis/RxSwiftCommunity/RxEventHub.svg?style=flat

**Comment by zzdjk6** [comment]
Sorry for that, already fixed it, thanks for point it out :)

**Comment by ashfurrow** [comment]
No problem! It all looks good, going to go ahead and close this issue. Thanks again!
