### ISSUE TITLE
RxGoogleMaps

### ISSUE THREAD

**Issue by inkyfox** [RxSwiftCommunity/contributors#15]
Hey guys,

I've just written RxGoogleMaps which is a Rx wrapper for GoogleMaps SDK.
https://github.com/inkyfox/RxGoogleMaps

It provides various reactive extensions for delegates and properties of GMSMapView and GMSOverlay. Because GoogleMaps SDK contains static binaries, it needs one more step after `pod install`, but it can be acceptable in general, I think.

Thanks

**Comment by ashfurrow** [comment]
Cool, awesome! I've invited you to the organization, the contributor guidelines and code of conduct are in the readme of this repository. Check this issue out for an example of how to move a project over: https://github.com/RxSwiftCommunity/contributors/issues/14 And let me know if I can be of any help!

**Comment by inkyfox** [comment]
Wow, great!

I have done items on checklist:

[x]Transfer the repo's ownership
[x]Fork the repo back to my personal account
[x]Update copyright in code
[x]Update copyright in LICENSE
[x]Update README
[x]Update podspecs with new remote URL

@ashfurrow

**Comment by ashfurrow** [comment]
Looks great, thanks! Let me know if there's anything else I can do to help!
