### ISSUE TITLE
RxFileMonitor (Mac)

### ISSUE THREAD

**Issue by DivineDominion** [RxSwiftCommunity/contributors#16]
https://github.com/CleanCocoa/RxFileMonitor

Put this up to get reactive file system events when monitoring a folder (or file). Pretty simple thing, really.

**Comment by ashfurrow** [comment]
Very cool, what a neat idea for a framework! [Here's an issue](https://github.com/RxSwiftCommunity/contributors/issues/15) where we've moved a project over to the org, if that's something you're interested in. I've invited you to the org, let me know if I can be of further assistance :bow:

**Comment by DivineDominion** [comment]
Will look into the checklist. I've got a small favor to ask, though: can you point me to naming conventions in the land of reactive/declarative programming? I was told `FileEvents.folder(...)` would be a better fit; I now see that `Monitoring.folderMonitor` carries my imperative training with it :) My next suggestion would be `Monitor.folderMonitor(url:)`.

**Comment by tonyarnold** [comment]
Why even have the class method? Could you not just init the FileMonitor instance?

**Comment by ashfurrow** [comment]
Yeah, either makes sense to me 👍 I prefer the instance like Tony suggests.

**Comment by DivineDominion** [comment]
By making the monitor type a subclass of `Observable`, that is? I cannot imagine the consequences, though. Could work, if you say that's idiomatic :)

**Comment by DivineDominion** [comment]
Here we go:

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] merge changes into community repo :)
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by DivineDominion** [comment]
@ashfurrow I thought I'd have write access after transferring ownership, but no :) Can you merge the PR or grant me write access to https://github.com/RxSwiftCommunity/RxFileMonitor to continue?

**Comment by ashfurrow** [comment]
Should be good now, sorry about that!

**Comment by DivineDominion** [comment]
Done with the migration, now comes integrating your feedback 👍
