### ISSUE TITLE
RxHttpClient

### ISSUE THREAD

**Issue by reloni** [RxSwiftCommunity/contributors#18]
Hello.
I made a little HttpClient with RxSwift. It's a wrapper for `URLSession`, it transforms session events (like `didReceiveResponse` or `didReceiveData`) into Observable events. 
I would be glad add this project to the community if it's suitable.
Project: https://github.com/reloni/RxHttpClient

**Comment by ashfurrow** [comment]
Cool, looks awesome! I've invited you to the organization, [here are instructions](https://github.com/RxSwiftCommunity/contributors#stewarding-a-project) on how you might transfer it to the GitHub organization. Let me know if I can be of any help!

**Comment by reloni** [comment]
@ashfurrow 
Hello. I think I did most of steps. But I don't understand this: add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io. What exactly should I do? 
And is it possible now for me to manage some additional settings as I can do with my own repositories: for example choosing protected branch, or choose additional status checks. My project had code coverage check (with codecov.io) and now it gone, is it possible to setup this things again?

**Comment by reloni** [comment]
I see that codecov check working. But managing integrations for repo requered admin rights, right?

**Comment by ashfurrow** [comment]
Awesome, good work! To add a project, add it to this file: https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/blob/source/data/items.yml . Not sure if admin status is required or not, I'll look into it 👍

**Comment by ashfurrow** [comment]
Aye, you need admin permissions to add the CodeCov webhook. You should have those permissions, let me know how it goes.

**Comment by reloni** [comment]
@ashfurrow 
Opened PR here: https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/pull/46
It seems I have completed all steps. Thanks for assistance:)

**Comment by ashfurrow** [comment]
Awesome! I've merged it – going to close this issue but please let me know if I can be of more help 👍
