### ISSUE TITLE
rxpager

### ISSUE THREAD

**Issue by pgherveou** [RxSwiftCommunity/contributors#19]
Hey there 
I created and published this repo to create simple Rx based pager.
Let me know if this could be a good fit for RxSwiftCommunity

https://github.com/pgherveou/rxpager

**Comment by ashfurrow** [comment]
Super cool! I'll add you to the organization and you can follow [this checklist](https://github.com/RxSwiftCommunity/contributors#checklist-for-transferring-ownership) to transfer things. Let me know if you have any questions!

**Comment by pgherveou** [comment]
Cool Thks for the invite @ashfurrow
