### ISSUE TITLE
RxViewModel

### ISSUE THREAD

**Issue by esttorhe** [RxSwiftCommunity/contributors#2]
I wrote [`RxViewModel`](https://github.com/esttorhe/RxViewModel) as a need for `ReactiveViewModel` but with `Rx` extensions.

Would it make sense to move it here?

If so how's the process?

Thanks to all the @RxSwiftCommunity/contributors for any input in this. :bow:

**Comment by ashfurrow** [comment]
Neat! I just moved NSObject+Rx over, and some notes are in [this issue](https://github.com/RxSwiftCommunity/NSObject-Rx/issues/3). Would you like to make a todo list of what needs to happen, we can double check everything, then do the todos?

**Comment by esttorhe** [comment]
Ace!
Since I'm no ownder/admin didn't know if I could create a repo here.

I'll create the todo as an issue in `RxViewModel` :+1:

**Comment by esttorhe** [comment]
@ashfurrow I created the `TODO` list here => esttorhe/RxViewModel#10

**Comment by ashfurrow** [comment]
@esttorhe since you're an owner of the org now, you should be able to manage the handoff from you to the org by yourself :cake:

**Comment by esttorhe** [comment]
I was thinking about it actually.

Initially I did give `admin` access to @RxSwiftCommunity/contributors but then follow the same pattern as `NSObject-Rx` where the `contributors` only have `Read` access.

Was waiting until we have a more defined «structure» before completely handling this down to whatever team should handle it.

I'm not :100: sure if giving total access to `contributors` is the idea or if we are planning on generating another team, etc.
