### ISSUE TITLE
RxTask

### ISSUE THREAD

**Issue by scottrhoyt** [RxSwiftCommunity/contributors#20]
[RxTask](https://github.com/scottrhoyt/RxTask) offers an RxSwift wrapper to launching tasks on the command line via `Foundation.Process`. The library has basic functionality, has good test coverage, is fully documented, and is available for consumption via Carthage or SPM.

While the existing functionality will work for most use cases, there are a couple of major features left to implement:

* Consume a `stdin` `Observable` for processes that take input.
* Port to Linux (currently there is some missing functionality in the Linux port of `Foundation` preventing this from being done easily).

Let me know what you guys think!

Progress:

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by ashfurrow** [comment]
Looks cool! I've invited you to the org, instructions for transferring the repo are [in the readme](https://github.com/RxSwiftCommunity/contributors#checklist-for-transferring-ownership), let me know if I can clarify anything or help!

**Comment by scottrhoyt** [comment]
Thanks @ashfurrow !
