### ISSUE TITLE
Introducing RxGRDB

### ISSUE THREAD

**Issue by groue** [RxSwiftCommunity/contributors#21]
Hello,

I wish the repository http://github.com/groue/RxGRDB would eventually join RxSwiftCommunity.

RxGRDB provides reactive extensions for [GRDB.swift](http://github.com/groue/GRDB.swift), the "toolkit for SQLite databases, with a focus on application development".

While GRDB is already pretty solid and fuels a few applications on the App Store, RxGRDB is still in the alpha stage. Yet if it would join RxSwiftCommunity in the future, we'd share some nice benefits:

- RxSwiftCommunity would support SQLite besides [Realm](https://github.com/RxSwiftCommunity/RxRealm) and [Core Data](https://github.com/RxSwiftCommunity/RxCoreData).
- RxGRDB would naturally evolve and talk to sibling repositories like [RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources).
- RxGRBD has no automatic UITableView and UICollectionView bindings yet, but the required database observation features are ready and battle-tested in GRDB itself.
- GRDB already has a strong focus on application development, and is pioneer in the landscape of protocol-oriented database libraries. Reactive programming is thus a pretty natural fit. See [How to build an iOS application with SQLite and GRDB.swift](https://medium.com/@gwendal.roue/how-to-build-an-ios-application-with-sqlite-and-grdb-swift-d023a06c29b3) for a general introduction to the non-reactive aspects of the library.

Let me know if you're interested!

**Comment by ashfurrow** [comment]
Great, looks cool! I've invited you to the org, here's a list of next steps: https://github.com/RxSwiftCommunity/contributors#checklist-for-transferring-ownership Let me know if we can help.

**Comment by groue** [comment]
It looks like [RxSwiftCommunity/RxGRDB](https://github.com/RxSwiftCommunity/RxGRDB) is live, now!

Thanks to all 👍
