### ISSUE TITLE
RxMotionKit

### ISSUE THREAD

**Issue by rsobolewski** [RxSwiftCommunity/contributors#23]
Hey!

3 months ago I have created a RxMotionKit 🏃 which is reactive wrapper based on RxSwift for CoreMotion framework. Today I have just discovered RxSwift community, and I think that it will be nice to contribute. Project can be installed with CocoaPods or Carthage.

Link for the repository: https://github.com/rsobolewski/RxMotionKit

Thanks!

**Comment by freak4pc** [comment]
Hey! Congrats and good job on all the work !

Could you clarify difference between this and [RxCoreMotion](https://github.com/RxSwiftCommunity/RxCoreMotion) ?

**Comment by rsobolewski** [comment]
I think this is a different approach. In my implementation you have lot more customizability and simple API. You can set independent update time interval for each sensor or device motion reference frame. In my approach end user don't know on underlying `CMMotionManager`.

Each access to sensor has individual implementation with common interface which is fully open to abstraction and testability. RxMotionKit with division of responsibility has no repeated code 😉

**Comment by freak4pc** [comment]
That sounds good! I like the API but I'm wondering why you're still using the old `rx_event` notation vs `rx.event`, while the former isn't used anymore AFAIK (I guess this is a specific thing we could address in a PR but its probably better to be "production ready") 

Anyways no reason not to migrate this into RxSwiftCommunity! 

Please copy paste the following checklist to your first post in this thread and make sure everything is checked out. 

```
- [ ] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [ ] replace copyright in README
- [ ] replace copyright in LICENSE
- [ ] update the remote URL of the Podspec (if any)
- [ ] update CI badge
- [ ] update CI settings
- [ ] transfer repository ownership (once you're a contributor)
- [ ] fork the repo back to your personal account
- [ ] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
```

**Comment by ashfurrow** [comment]
Hi @rsobolewski! Just wondering if there's anything I can do to help follow-up on this? Let me know what I can do, and sorry for the delay!

**Comment by vandadnp** [comment]
I'm assuming we can close this issue?

**Comment by ashfurrow** [comment]
Yup, let's close. @rsobolewski can re-open if they'd like any help.
