### ISSUE TITLE
RxState

### ISSUE THREAD

**Issue by nazeehshoura** [RxSwiftCommunity/contributors#24]
Hey!

I have created a [RxState](https://github.com/nazeehshoura/RxState) - A Redux implementation in Swift using RxSwift. Would be a nice addition to RxSwiftCommunity projects :)

Thanks!

**Comment by ashfurrow** [comment]
Hey there, looks cool! I've invited you to the GitHub organization; the notes in this repo's readme include the steps to transfer a project. Let me know if I can help!

**Comment by ashfurrow** [comment]
Hey @nazeehshoura – it looks like this has been finished, so I'm going too lose the issue. Please re-open if there's anything more to discuss. And thanks again for being a part of our organization!
