### ISSUE TITLE
RxCloudKit

### ISSUE THREAD

**Issue by maxvol** [RxSwiftCommunity/contributors#26]
https://github.com/maxvol/RxCloudKit

i believe my project belongs in RxSwiftCommunity.

it is not sufficiently tested yet, but is pretty mature by now (i personally do use it in a few personal projects that are scheduled for production this fall).

cheers, Maxim

### Checklist for Transferring Ownership

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [ ] update the remote URL of the Podspec (if any)
- [ ] update CI badge
- [ ] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by freak4pc** [comment]
Hey Maxim, I added the Conformance Checklist to your original post. Could you make sure you follow the entire list and make sure you're covered there ?

**Comment by ashfurrow** [comment]
Hi @maxvol – it doesn't look like anyone has added you to the org yet, preventing us from moving forward on this. Are you still interested? Let me know and I'll help out!

**Comment by maxvol** [comment]
Hi @ashfurrow - yes I am still interested, although I decided to postpone ownership transfer until the codebase is more mature. I am using it in a few projects, one of which is live for about a month or so, but I am still making compatibility-breaking changes.

Perhaps you can add me to the org anyway because I would like to contribute to RxCoreData and some other projects as well. My pull-request for RxCoreData is hanging there for about a month already - https://github.com/RxSwiftCommunity/RxCoreData/pull/23

**Comment by ashfurrow** [comment]
Cool cool – thanks again and let me know if I can help.
