### ISSUE TITLE
Peril Integration

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/contributors#28]
[Peril](https://github.com/danger/peril) is like [Danger](http://danger.systems) except it's hosted and is applied org-wide. Basically what I'm proposing is we take common issues from pull requests and apply them to _all_ RxSwiftCommunity repos. 

Things like:

- Making sure a changelog entry exists.
- Making sure the PR has an accompanying description.
- Making sure podspec changes and cartfile changes are done in parallel.
- Spell-checking readmes.

We can chat about other uses too. What do you think @RxSwiftCommunity/contributors ?

**Comment by esttorhe** [comment]
Makes sense. 
I like standardizing the whole org. 

Where would this love though? Heroku?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ashfurrow** [comment]
Yeah exactly. Peril's [setup docs](https://github.com/danger/peril/blob/master/docs/setup_for_org.md) specifically target Heroku. I'm happy to host it on my Heroku account and set it up 😄

**Comment by ashfurrow** [comment]
Okay @RxSwiftCommunity/contributors we now have Peril running in production that checks pull requests for changelog changes (if applicable, see [here](https://github.com/RxSwiftCommunity/peril/pull/1) for details). If you see anything strange, please just ping me in the PR!
