### ISSUE TITLE
RxTestExt

### ISSUE THREAD

**Issue by mosamer** [RxSwiftCommunity/contributors#33]
https://github.com/mosamer/RxTestExt

This project aims to add some helpers commonly used while testing Rx code, something similar to `RxSwiftExt` but for `RxTest` instead.

Currently, it contains an example project to demonstrate its usage. There is no test coverage yet, but I should be working on [it](https://github.com/mosamer/RxTestExt/issues/1) soon.

This project should be evolving to include more features and to improve existing ones, though being part of RxSwiftCommunity makes perfect sense. I am also open to move it as a subspec of `RxSwiftExt` if it makes more sense.

Feel free to let me know if you have any questions or comments, and I will be working on the following checklist.

Regards :-)

### Checklist for Transferring Ownership

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [ ] replace copyright in README
- [ ] replace copyright in LICENSE
- [ ] update the remote URL of the Podspec (if any)
- [ ] update CI badge
- [ ] update CI settings
- [ ] transfer repository ownership (once you're a contributor)
- [ ] fork the repo back to your personal account
- [ ] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by freak4pc** [comment]
@mosamer Just out of curiosity would you mind showing the RxBlocking equivalent of some RxTestExt code - so it's easy to understand what your library aims to solve?

**Comment by mosamer** [comment]
@freak4pc I am not sure if this is possible, mainly due the differences between RxBlocking & RxTest themselves. However, taking this code snippet from Action test cases, it can be modified as shown.
```diff
describe("completable action") {
   var action: CompletableAction<String>!
   beforeEach {
      let work: Completable = Observable<Never>.empty().asCompletable()
      action = CompletableAction {_ in work }
-      scheduler.scheduleAt(10) { action.inputs.onNext("a") }
-      scheduler.scheduleAt(20) { action.inputs.onNext("b") }
+      scheduler.bind([next(10, "a"), next(20, "b")], to: action.inputs)
   }
   it("inputs subject receives generated inputs") {
-      let inputs = scheduler.createObserver(String.self)
-      action.inputs.bind(to: inputs).disposed(by: disposeBag)
+      let inputs = scheduler.record(source: action.inputs)
      scheduler.start()
-      XCTAssertEqual(inputs.events, [
-         next(10, "a"),
-         next(20, "b"),
-      ])
+      assert(inputs).next(times: 2)
   }
   it("emits nothing on elements") {
-      let elements = scheduler.createObserver(Never.self)
-      action.elements.bind(to: elements).disposed(by: disposeBag)
+      let elements = scheduler.record(source: action.elements)
      scheduler.start()
+      assert(elements).not.next()
-      XCTAssertEqual(elements.events.count, 0)
   }
}
```

**Comment by freak4pc** [comment]
Sorry, I meant RxTest :) It was late 😴 

Anyways, cool! looks like nice syntactical sugar :) 

by the way 
`assert(inputs).next(times: 2)` isn't the same as asserting "a" and "b" and 10 and 20 :) 
But other than that looks pretty clean. 

I think the approach of `RxSwiftExt/Core` & `RxSwiftExt/Tests` could be really cool, but it depends on whether or not @fpillet agrees with this approach. I'm also not 100% sure how this works for Carthage and SPM - it might make it less obvious

**Comment by mosamer** [comment]
@freak4pc 
> assert(inputs).next(times: 2) isn't the same as asserting "a" and "b" and 10 and 20 :)

I know :) that's why I'll try to add [this](https://github.com/mosamer/RxTestExt/issues/8) or [this](https://github.com/mosamer/RxTestExt/issues/6) hopefully soon :)

I also agree on the discoverability concern, so would appreciate second opinion here.

**Comment by freak4pc** [comment]
@mosamer Looking more into this I really like some of the implementation you made here. 

I would really hope to get some more feedback from @RxSwiftCommunity/contributors regarding some of the questions raised, but, given no other replies in the next 3 days I feel comfortable migrating this repo to the main organization if you'd want to.

**Comment by freak4pc** [comment]
BTW just because I'm writing some tests right now - I would rename 
`assert(elements).not.next()`

to either
`assert(elements).never()`

or
`assert(elements).nothing()` 

I think the first option makes more sense in Swift context:)

**Comment by mosamer** [comment]
Done 🎉
