### ISSUE TITLE
Remove Aeryn server

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/contributors#36]
Once https://github.com/RxSwiftCommunity/contributors/issues/28 is completed, we can move away from [Aeryn](https://github.com/Moya/Aeryn). (Aeryn is the thing that invites new contributes to join the organization once their first PR is merged). 

Why retire Aeryn? Well,, Aeryn is configured per-repo and many of our repos don't have it at all. Using Peril, we can centralize this.

**Comment by freak4pc** [comment]
👍 Sounds good !

**Comment by ashfurrow** [comment]
The relevant code to do this is here: https://github.com/danger/peril-settings/blob/fc0015452438c8a1624c0951a600f723f2e60fea/org/aeryn.ts#L18-L39 I'll try to get to this today.

**Comment by ashfurrow** [comment]
Okay, this is done and tested!

**Comment by ashfurrow** [comment]
This is also possible on personal, non-org repos: https://github.com/ashfurrow/peril-settings/blob/master/rules/aeryn.ts
