### ISSUE TITLE
Add RxFlow

### ISSUE THREAD

**Issue by twittemb** [RxSwiftCommunity/contributors#37]
- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by ashfurrow** [comment]
Very cool! Really nice readme! Looks like we're all set then?

**Comment by twittemb** [comment]
Hi @ashfurrow ... Yes it seems good to me: CocoaPods and Carthage are ok. 

Thanks.

**Comment by freak4pc** [comment]
Looks like all good and moved ! Thanks @twittemb . Looking forward to checking your project tomorrow :)
