### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by twittemb** [RxSwiftCommunity/contributors#38]
Hi,

I think the Slack channel in the README is wrong.
I think it should be https://rxswift.slack.com.

Am I wrong ?

Thanks.

**Comment by ashfurrow** [comment]
Good catch – could have worked at one point but not now! Want to open a PR?

**Comment by twittemb** [comment]
@ashfurrow I just did : https://github.com/RxSwiftCommunity/contributors/pull/40

Thanks 👍

**Comment by freak4pc** [comment]
Fixed by #40.
