### ISSUE TITLE
Action

### ISSUE THREAD

**Issue by ashfurrow** [RxSwiftCommunity/contributors#4]
I've just published the first release of [Action](https://github.com/ashfurrow/Action), an abstraction on top of observables. Basically `Action` or `RACCommand` from ReactiveCocoa.

It's only a 0.1.0 release, since there are some [issues that need to be dealt with first](https://github.com/ashfurrow/Action/milestones/Production%20Readiness). Once they're all addressed, we can continue the conversation to move Action over to this organization.

**Comment by ashfurrow** [comment]
All production-readiness issues are complete. @RxSwiftCommunity/contributors Anyone opposed to me moving this over to the community org?

**Comment by esttorhe** [comment]
I'm on board on moving this over :+1: 
:shipit:

**Comment by orta** [comment]
:+1:
