### ISSUE TITLE
RxASDataSources

### ISSUE THREAD

**Issue by dangthaison91** [RxSwiftCommunity/contributors#43]
https://github.com/dangthaison91/RxASDataSources

### Checklist for Transferring Ownership

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [ ] update CI badge
- [ ] update CI settings - Pending CI configuration
- [x] transfer repository ownership (once you're a contributor)
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by freak4pc** [comment]
CI Badge and Settings are irrelevant as project has no tests yet.
Project now lives in https://github.com/RxSwiftCommunity/RxASDataSources
