### ISSUE TITLE
RxTheme

### ISSUE THREAD

**Issue by wddwycc** [RxSwiftCommunity/contributors#45]
My colleague was using [SwiftTheme](https://github.com/jiecao-fm/SwiftTheme) on iOS, 
but the lib is very hard to extend and its implementation is not that clean.

I know RxCocoa is perfect for such binding switch, 
so I write this lightweight lib with a `ThemeService<T>` class and a bunch of `Binder<T>` presets.

https://github.com/wddwycc/RxTheme

It's now used in most downloaded coin analysis app in Japan  [Coinview](https://www.coinjinja.com/coinview)

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by ashfurrow** [comment]
Looks awesome! I've invited you to the org, let me know what we can do to help!

**Comment by freak4pc** [comment]
Welcome @wddwycc ! As @ashfurrow mentioned, let us know if you need help in transferring ownership. 

There's one extra step that we didn't update in the documentation: 

- [x] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner community@rxswift.org`.

You can read more on this decision [here](https://github.com/RxSwiftCommunity/contributors/issues/44) but I also plan on updating the entire documentation for this soon :)

**Comment by wddwycc** [comment]
@ashfurrow @freak4pc  thank you guys.

**Comment by wddwycc** [comment]
@ashfurrow @freak4pc 

Finished tasks and [PR is here](https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/pull/74)

**Comment by bobgodwinx** [comment]
Really nice I love the idea, congrats. 👍  next is to support `Carthage` if you can. But no rush. you can create an issue and someone can pick it up from there.

**Comment by freak4pc** [comment]
Closing this one. Thanks @wddwycc !
