### ISSUE TITLE
RxFirebase

### ISSUE THREAD

**Issue by arnauddorgans** [RxSwiftCommunity/contributors#48]
- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [ ] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
- [x] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

**Comment by freak4pc** [comment]
Thanks @arnauddorgans  - I invited you to the organization, feel free to complete the process and let us know if you need any and all help :) 

Please also make sure to fix your CI since its broken at the moment :)

**Comment by freak4pc** [comment]
@arnauddorgans I've also archived RxFirebase and renamed it RxFirebase-Deprecated so you should have no issues of transferring with the same name.

**Comment by SD10** [comment]
Yeah, I have to figure out how to fix CI for projects with Firebase as a dependency because I'm having the same issue. I don't know much about travis but it looks like the CocoaPods version is out of date.
