### ISSUE TITLE
RxContacts

### ISSUE THREAD

**Issue by satishbabariya** [RxSwiftCommunity/contributors#49]
https://github.com/satishbabariya/RxContacts/
RxContacts is a RxSwift wrapper around the Contacts Framework. 

I believe my project belongs in RxSwiftCommunity.

**Comment by freak4pc** [comment]
Hey Satish! Looks great :) 
Can you please paste in the checklist from the contribution guide and make sure you follow all of the steps ? 

Thanks !
Shai

**Comment by satishbabariya** [comment]
- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [X] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
- [X] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

**Comment by freak4pc** [comment]
Can you do the last 2 steps ? @satishbabariya

**Comment by satishbabariya** [comment]
Done. and Done.

**Comment by freak4pc** [comment]
@satishbabariya Hey buddy - I just invited you as a Member of RxSwiftCommunity. Once you accept, feel free to complete the transfer ownership step and fork the repo back to your personal account. 

Once this is done you may close this issue as this is all done :) 

Thank you for your contribution, and welcome to RxSwiftCommunity!
Shai.

**Comment by freak4pc** [comment]
Hey @satishbabariya , I actually don't see it in our community website: http://community.rxswift.org

Can you open a PR to add it there as well? You can take this as inspiration: https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/pull/81

**Comment by satishbabariya** [comment]
Also, do I need to release new pod version?

**Comment by satishbabariya** [comment]
Oh! is this one? , https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/pull/80

**Comment by freak4pc** [comment]
@satishbabariya I think you would as it points to a different repository ?
