### ISSUE TITLE
Repo for projects that support RxSwift

### ISSUE THREAD

**Issue by thanegill** [RxSwiftCommunity/contributors#5]
How do you all feel about creating a repo similar to [awesome-swift](https://github.com/matteocrippa/awesome-swift) for projects that support RxSwift? We could include repos under RxSwiftCommunity's control, maybe even make it the "landing page" for this community.

These libraries come to mind:
- [Moya](https://github.com/Moya/Moya)
- [FirebaseRxSwiftExtensions](https://github.com/mbalex99/FirebaseRxSwiftExtensions)
- [Parse-RxSwift](https://github.com/bluelinelabs/Parse-RxSwift)
- [Moya-ObjectMapper](https://github.com/ivanbruel/Moya-ObjectMapper)
- [RxEasing](https://github.com/lintmachine/RxEasing)

And these projects:
- [Eidolon](https://github.com/artsy/eidolon)
- [ReactiveWeatherExample](https://github.com/marinbenc/ReactiveWeatherExample)

**Comment by ashfurrow** [comment]
Neat idea!

**Comment by esttorhe** [comment]
I like this; having it under the `RxSwiftCommunity` umbrella seems natural as well.

Should we fire up the repo and start adding things to it @RxSwiftCommunity/contributors ?

**Comment by ashfurrow** [comment]
Seems legit! Esteban, do you want to set that up? I imagine we could add @psophis to the contributors list so they could help out, too.

**Comment by thanegill** [comment]
What should the repo name be?

If it's acting as a landing page is should probably be "RxSwiftCommunity".

**Comment by ashfurrow** [comment]
I wonder if this should have any web presence? Like a basic site on rxswiftcommunity.github.io ? It'd be easy to store in a yaml file ([example](https://github.com/ashfurrow/blog/blob/master/data/talks.yml)). Thoughts?

**Comment by thanegill** [comment]
Now that is a good idea! Maybe a little harder to maintain, but a better way none the less.

Octopress/Jekyll?

**Comment by esttorhe** [comment]
Personally I'm not a fan of `Jekyll`/`Octopress`.

`Hugo` or `Hexo` maybe?

I'm going to create a repo called `RxProjects` and will leave it empty and keep moving there.

Any objections?

**Comment by thanegill** [comment]
Anyway is fine with me.

If you want to use [github pages](https://pages.github.com) it needs to be named rxswiftcommunity.github.io.

**Comment by esttorhe** [comment]
yeah i know but since is not a definitive that we will be using github pages i thought calling it something else for now and rename it if we decide to go that route

**Comment by esttorhe** [comment]
Here it is: https://github.com/RxSwiftCommunity/RxProjects

**Comment by thanegill** [comment]
Great! I'll close this and open some issues over there for more specific topics.

**Comment by esttorhe** [comment]
:+1: :tada:
