### ISSUE TITLE
Add RxReduce

### ISSUE THREAD

**Issue by twittemb** [RxSwiftCommunity/contributors#50]
- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by freak4pc** [comment]
Hey @twittemb , you're missing this: 
- [ ] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

Can you confirm you've done it? :) 

Thank you!

**Comment by twittemb** [comment]
Hi @freak4pc 

I just did 👍

**Comment by freak4pc** [comment]
Looks good to me !  Closing this
