### ISSUE TITLE
RxBiBinding

### ISSUE THREAD

**Issue by Davarg** [RxSwiftCommunity/contributors#51]
Hello, guys
I've created solution for bidirectional binding https://github.com/Davarg/RxBiBinding
This solution is based on ReactiveCocoa (Obj-C version)
I think this will be useful for somebody

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
- [x] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

**Comment by ashfurrow** [comment]
Awesome! Sorry for the delay in responding – I've been really busy lately. I've invited you to the org so you should be able to move forward on this list. Let me know if I can help!

**Comment by freak4pc** [comment]
Hey @Davarg - Just saw this and noticed a few issues: 

1. You're using Variable which is currently on path to deprecation, I would suggest avoiding this. 
2. The Bi-Binding operator exists in the main repo as an example written by Kruno. Might want to take a look there for some inspiration? 

Just a thought. Thanks for the contribution!

**Comment by Davarg** [comment]
@ashfurrow @freak4pc  thanks guys.
1. I will replace Variable with something appropriate
2. Hmm, I will checkout this implementation, I think you mean this https://github.com/ReactiveX/RxSwift/blob/master/RxExample/RxExample/Operators.swift . Before I started my project I've looking solutions for Bi-Binding and all of them are had same issue with duplicated value.

   I will try to explain: (A) ---> (B) [:PROBLEM: (B) return value to ---> (A)]
   where A and B some observable values
   My solution is trying to avoid this situation

**Comment by Davarg** [comment]
@ashfurrow Hello, I've completed all requirements from checklist, so should I close this ticket?

**Comment by freak4pc** [comment]
Thanks !
