### ISSUE TITLE
RxLocalizer

### ISSUE THREAD

**Issue by khambir** [RxSwiftCommunity/contributors#52]
I would like to add https://github.com/khambir/RxLocalizer to RxSwiftCommunity. This pod will help developers to localize their apps, using RxSwift 🚀. Also users are able to force application language to non-system one on the fly, without restarting the application.

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
- [x] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

**Comment by ashfurrow** [comment]
Cool! I've invited you to the organization. Let me know if you have any questions, you should be all set to proceed with that list!

**Comment by khambir** [comment]
Hi, @ashfurrow! I've already done all tasks from the checklist.

**Comment by ashfurrow** [comment]
Great work! Let's close this issue then?

**Comment by khambir** [comment]
@ashfurrow yes, thank you
