### ISSUE TITLE
RxCocoa-Texture

### ISSUE THREAD

**Issue by GeekTree0101** [RxSwiftCommunity/contributors#54]
### RxCocoa Extension Library for Texture. (a.k.a AsyncDisplayKit)

repo url: https://github.com/Geektree0101/RxCocoa-Texture
medium: https://medium.com/@h2s1880/texture-rxswift-interactive-wrapper-d3c9843ed8d7

> ## Checklist for Transferring Ownership
- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io

**Comment by GeekTree0101** [comment]
add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
link: https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/pull/87

**Comment by GeekTree0101** [comment]
https://github.com/RxSwiftCommunity/RxCocoa-Texture 
transfer repository ownership

**Comment by GeekTree0101** [comment]
https://github.com/GeekTree0101/RxCocoa-Texture
 fork the repo back to your personal account

**Comment by ashfurrow** [comment]
🎉
