### ISSUE TITLE
Request append RxSwiftCommunity/RxCocoa-Texture contributor 

### ISSUE THREAD

**Issue by GeekTree0101** [RxSwiftCommunity/contributors#55]
RxCocoa-Texture is constantly almost being maintained by Vingle iOS Developers.
https://github.com/RxSwiftCommunity/RxCocoa-Texture
I hope that @OhKanghoon will be added as a contributor.
https://github.com/OhKanghoon

Thank you.

**Comment by ashfurrow** [comment]
Hi @GeekTree0101 – contributors are automatically invited to the RxSwiftCommunity GitHub organization after they send a pull request to any of our repos and that PR gets merged. Are you looking for help maintaining that project? What can we do to support you?

**Comment by GeekTree0101** [comment]
Oh i got it! Thank you. I will feedback to my colleague.
