### ISSUE TITLE
Extend UIAlertController with RxSwift

### ISSUE THREAD

**Issue by keisukeYamagishi** [RxSwiftCommunity/contributors#56]
# Extend UIAlertController with RxSwift

## Overview

UIAlertController can be called from the extension of UIViewController using Rx.

## Checklist for Transferring Ownership

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
- [x] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

## issue

We would like to contribute this to RxCommunity.

We would appreciate your comments and requests.

best regards

## Current repository location

[keisukeYamagishi/RxAlert](https://github.com/keisukeYamagishi/RxAlert)

**Comment by ashfurrow** [comment]
Great, thanks! I've invited you to the GitHub organization.

**Comment by keisukeYamagishi** [comment]
@ashfurrow 
All check items Done 🎉

**Comment by ashfurrow** [comment]
Nice, well done! Thanks again!
