### ISSUE TITLE
Request RxCocoa-Texture write authority

### ISSUE THREAD

**Issue by OhKanghoon** [RxSwiftCommunity/contributors#66]
Hello @freak4pc 

I need `RxCocoa-Texture` repository write authority

**References**
- #55 
- Cocoapods Maintainer (https://cocoapods.org/pods/RxCocoa-Texture)

**Comment by freak4pc** [comment]
Hey @OhKanghoon - once you have a PR merged, you will be automatically added to the organisation. Is there anything else you're missing?

**Comment by OhKanghoon** [comment]
@freak4pc 
Umm.. I don’t have authority to push , tag, release in RxCocoa-Texture

Should I ask you to granted this authority?

**Comment by freak4pc** [comment]
Can you try now? I've added you @OhKanghoon

**Comment by OhKanghoon** [comment]
Thanks  👍🏻👍🏻❤️❤️
