### ISSUE TITLE
RxBatteryManager 🔋

### ISSUE THREAD

**Issue by mustafagunes** [RxSwiftCommunity/contributors#68]
Hello!

I recently felt the need to write this library and started using it in my own project. I have presented this to the benefit of everyone by sharing it publicly. But I believe it would be much more beneficial for the community to publish it. Project can be installed with SPM or CocoaPods 🎉

Repo: https://github.com/mustafagunes/RxBatteryManager

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [x] update the remote URL of the Podspec (if any)
- [x] update CI badge
- [x] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
- [x] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

**Comment by mustafagunes** [comment]
@freak4pc

**Comment by ashfurrow** [comment]
Cool! I have invited you to the GitHub organization, please follow the steps here: https://github.com/RxSwiftCommunity/contributors#checklist-for-transferring-ownership Let us know if we can help!

**Comment by mustafagunes** [comment]
@ashfurrow Thank you, I'll follow the rules on the list as soon as I can 😊

**Comment by freak4pc** [comment]
Sorry for not getting to this earlier! Thanks @ashfurrow for taking care of this :) 
Let us know if we can help in any way.

**Comment by mustafagunes** [comment]
@ashfurrow @freak4pc I've done the necessary tasks. Would you check :)

**Comment by freak4pc** [comment]
Thanks, and welcome :)
