### ISSUE TITLE
RxSocket.io is the only Rx library for socket.io

### ISSUE THREAD

**Issue by behrad-kzm** [RxSwiftCommunity/contributors#69]
very simple use-cases for working with socket.io

- [x] replace copyright with "Copyright (c) RxSwiftCommunity" in code
- [x] replace copyright in README
- [x] replace copyright in LICENSE
- [ ] update the remote URL of the Podspec (if any)
- [ ] update CI badge
- [ ] update CI settings
- [x] transfer repository ownership (once you're a contributor)
- [x] fork the repo back to your personal account
- [x] add project to https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io
- [x] Add `community@rxswift.org` as an owner of your project's CocoaPod by using `pod trunk add-owner YourPodName community@rxswift.org`.

**Comment by ashfurrow** [comment]
Very cool! Could have used this for sure on a project 😄 I just sent over an invitation. Once the repo is transferred over we can merge https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/pull/118
