### ISSUE TITLE
RxMKMapView

### ISSUE THREAD

**Issue by sger** [RxSwiftCommunity/contributors#7]
Hello,

I'm new to RxSwift decided to create this little project https://github.com/sger/RxMKMapView

RxMKMapView is a RxSwift wrapper for MKMapView (MapKit) delegate.

Thanks

**Comment by ashfurrow** [comment]
Super, looks really cool! Are you interested in moving it to the organization or would you just like it added to http://community.rxswift.org ?

**Comment by esttorhe** [comment]
I think we could add it to the website anyways (unless @sger doesn't want to)

**Comment by sger** [comment]
@ashfurrow yes i'm interested add it to the organization
@esttorhe i want to 

Thanks guys

**Comment by ashfurrow** [comment]
Cooooool! @esttorhe do you want to help transferring this to the org? If you're busy I can take point on that.

**Comment by esttorhe** [comment]
I can tackle this. I'm actually adding the project to the website.

@sger just so we are clear; moving the project to the organization will require you to transfer ownership of the repo/project to the organization.

We will add you to the organization as well (if you want and accept it) and you'd get push access, etc.

Let me know if you don' t know how to do it and I would help you.
You could start by creating an issue here or on your repo referencing the move and then we can move forward from there :smile:

**Comment by sger** [comment]
@esttorhe i'm ok move the project

**Comment by esttorhe** [comment]
:tada: 

Ok @sger you'll need to go to your repo; open settings and scroll down to the «Danger Zone» and click on `Transfer`:

<img width="790" alt="screen shot 2016-01-06 at 9 55 41 a m" src="https://cloud.githubusercontent.com/assets/2642850/12146858/af2a70e6-b45b-11e5-9f42-ebbb3739ff5b.png">

Then select/type `RxSwiftCommunity` and then let me know and I can accept that and add you to the team, etc

**Comment by sger** [comment]
@esttorhe i'm getting "You don’t have admin rights to RxSwiftCommunity" message

**Comment by esttorhe** [comment]
:joy: duuuuuh. sorry.

Adding you right now

**Comment by esttorhe** [comment]
@sger done :smile:

**Comment by sger** [comment]
@esttorhe done thanks man

**Comment by esttorhe** [comment]
:tada: Thanks @sger !!

Here's the repo on its new home :smile: 
https://github.com/RxSwiftCommunity/RxMKMapView

I'm running `middleman` locally to test the addition of this project to the website and will issue a `PR` soon

**Comment by sger** [comment]
@esttorhe cool :smiley:

**Comment by esttorhe** [comment]
Here's the `PR` that adds the project to the website => RxSwiftCommunity/rxswiftcommunity.github.io#27

In case @sger want to do the honors :wink:
